---
- hosts: all
  become: true
  tasks:
  - name: install apache package
    apt:
     name: apache2  
     state: latest
    when: ansible_distribution == "Ubuntu"  
  - name: update apache
    apt:
     name: libapache2-mod-php
     state: latest
    when: ansible_distribution == "Ubuntu"



  - name: install apache package
    dnf:
     name: httpd
     state: latest
    when: ansible_distribution == "CentOS"
  - name: update apache
    dnf:
     name: php
     state: latest
    when: ansible_distribution == "CentOS"
