---
- hosts: all
  become: true
  tasks:
  - name: install apache package
    apt:
     name: apache2  
     state: latest
  - name: update apache
    apt:
     name: libapache2-mod-php
     state: latest
