---
- hosts: all
  become: true
  tasks:

  - name:  update repository index for ubuntu
    apt:
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages ubuntu
    apt:
     name: 
      - apache2
      - libapache2-mod-php

     state: latest
    when: ansible_distribution == "Ubuntu"

  
  - name:  update repository index for centos
    dnf:
     update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache and php packages  centos
    dnf:
     name: 
      - httpd
      - php
     state: latest
    when: ansible_distribution == "CentOS"
  
 
