---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
     update_cache: true

  - name: remove apache package
    apt:
     name: httpd  
     state: absent
  - name: remove  update apache
    apt:
     name: libapache2-mod-php
     state: absent
