---
- hosts: all
  become: true
  pre_tasks:  

  - name: update centos
    tags: always
    dnf:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "CentOS"


  - name: update ubuntu
    tags: always
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  
  become: true
  tasks:
  - name: install apache and php packages  centos
    tags: centos, httpd, apache

    dnf:
     name:
      - httpd
      - php
     state: latest
  - name: copy files to webserver
    tags: centos, httpd, apache

    copy: 
     src: default_site.html
     dest: /var/www/html/index.html
     owner: root
     group: root
     mode: 0644

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb ubuntu
    tags: ubuntu, db, mariadb
    apt:
     name: mariadb-server
     state: latest
   

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package ubuntu
    tags: samba, ubuntu
    apt:
     name: samba
     state: latest
    
 
